from typing import Optional, List, Dict

class HtmlNode:
    def to_html(self) -> str: ...

class LeafNode(HtmlNode):
    def __init__(self, tag: Optional[str], value: Optional[str], props: Optional[Dict[str, str]] = None) -> None: ...
    def to_html(self) -> str: ...

class ParentNode(HtmlNode):
    def __init__(self, tag: str, children: List[HtmlNode], props: Optional[Dict[str, str]] = None) -> None: ...
    def to_html(self) -> str: ... 